project_id = "uttnlfgoxwgzogtsskbk"

[functions.judgeme-health]
verify_jwt = false

[functions.shopify-product]
verify_jwt = false

[functions.shopify-collection]
verify_jwt = false

[functions.shopify-products]
verify_jwt = false

[functions.shopify-blog]
verify_jwt = false

[functions.shopify-journal]
verify_jwt = false

[functions.shopify-home-banners]
verify_jwt = false

[functions.shopify-lead-capture]
verify_jwt = false
